### PR TITLE
Add a format parameter to tree.php and support JSON output.

### PR DESCRIPTION
**Pull request by Osmose**
This fixes the issues with `tree.php` on older PHP versions like what we're running on the server.

@tofumatt r?

### CODE REVIEW

**Comment by floatingatoll** [comment]
r+, will update #20 and #21 to include it.

**Comment by floatingatoll** [comment]
Hi, it's me again, your "generating annoying work for everyone" companion.

Pull request #19 was reverted due to the syntax incompatibility as noted above, and removed from production. If you could please combine the original patch from pull request #19 and the fixed commit above, and resubmit them to this pull request, I'm going to repurpose this one to continue the work of #19.

**Comment by Osmose** [comment]
> If you could please combine the original patch from pull request #19 and the fixed commit above, and resubmit them to this pull request, I'm going to repurpose this one to continue the work of #19.

Done!

**Comment by tofumatt** [comment]
@floatingatoll is this good to merge now? You were the original reviewer so I'll leave it to you.

**Comment by april** [comment]
Hello!  Your friendly neighborhood infosec person here!

Can I ask why this is necessary?  I'm unclear as to why we need to be able to download our entire employee directory.  Being able to understand the need here would go a long ways towards helping me understand.

Thanks so much!  :)

**Comment by Osmose** [comment]
My primary use case is wanting to write a script that tracks diffs in the org tree week to week and generates a report to help stay updated with how the org is changing over time. I know that there are scripts that already do this with the HTML page, converting it to JSON just makes it a little easier to parse.

Other use cases include things like generating a list of managers ordered by the number of direct reports they have, or building a list of self-reported job titles. Nothing organizationally needed, but mildly useful bits of info for anyone curious about the org tree.

**Comment by floatingatoll** [comment]
I'd rather we implement that through direct LDAP access, so that we're not granting a thousand people the ability to dump the underlying phonebook data in bulk to permit it for one or two limited use cases.

**Comment by april** [comment]
I agree with @floatingatoll that direct, explicitly authorized LDAP access is best.  Can I ask who is using that information, currently?

**Comment by Osmose** [comment]
I don't have a list or anything of who is using the info. Honestly with this pushback I'd rather drop this PR and either live without the info or scrape it from the HTML. That'd be preferable to direct LDAP access anyway.

**Pull request closed without merging**
