### PR TITLE
Allow punctuation characters in names.

### PR DESCRIPTION
**Pull request by chutten**
Not all names contain only letter-class characters.

### CODE REVIEW

**Comment by chutten** [comment]
...would this open it up to vulnerabilities?

**Comment by chutten** [comment]
This is in support of [bug 1053018](https://bugzilla.mozilla.org/show_bug.cgi?id=1053018).

**Comment by tofumatt** [comment]
I’m a bit behind on pull requests on this repo but know this is on my radar. I’ll have a look this week, promise :-)

**Comment by tofumatt** [comment]
My thoughts would be to test this locally and see if it lets you do bad stuff with LDAP. I'll admit the code is rough around the edges and I'm not sure how well-sanitised the input always is.

Are you able to test it locally using the dev server + VPN?

**Comment by chutten** [comment]
"you" meaning me? No, sorry. I have no knowledge of them.

**Comment by tofumatt** [comment]
Okay. Sorry I’m so late on this, I want it fixed too.

I’ll try this over the weekend.

**Comment by mozfreddyb** [comment]
`\p{P}` seems to allow quite a range of characters that are valid for LDAP Syntax.
I think this PR could be a great opportunity to start using [ldap_escape()](https://secure.php.net/ldap_escape).

**Comment by floatingatoll** [comment]
Our restriction to PHP 5.3 + vendor patches means that we can't simply use ldap_escape() without taking extra steps. The author of PHP's official ldap_escape() provided a version that's drop-in compatible with our codebase at 

http://stackoverflow.com/questions/8560874/php-ldap-add-function-to-escape-ldap-special-characters-in-dn-syntax/8561604#8561604

And so I suggest we use that to make this happen.

**Comment by floatingatoll** [comment]
The pull request is refused at this time as we should not be replacing regexes with other regexes. I concur that the ldap_escape() implementation is appropriate, but I can't update this pull request with my commit 0218cdf7a8765bb5ab09b5e187737f88524053c6 that implements it. So I'm going to close this, and open an issue instead. Sorry for the noise.

**Pull request closed without merging**
