### PR TITLE
Bug 540246 - Handle space as delimiter of keywords.

### PR DESCRIPTION
**Pull request by upsuper**

### CODE REVIEW

**Comment by tofumatt** [comment]
I love the loop to add the escape bit to the attributes; much cleaner :+1: 

Sorry but I'm a bit rusty on my LDAP, so how does this change the search functionality? What's an example of how it worked before and how it works now?

Cheers!

**Comment by upsuper** [comment]
It changes the way how whitespaces are handled.

Currently, if you search like "Foo Bar", it only matches a person if they have any field contains the whole string "Foo Bar". With this change, it matches a person if they have any field contains "Foo" and also have any field contains "Bar".

I guess it might be probably better to swap the inner and the outer loop so that it matches any field contains both "Foo" and "Bar" instead.

The downside is that, the filter string becomes longer and it may take longer time to search if there are too many whitespaces inserted.

**Comment by tofumatt** [comment]
Does it do the same for the name field? Being able to get an exact result for someone’s name is useful, so if this doesn’t give me all Matts when I search “Matt MacPherson” then I’d say it’s good :-)
- tofumatt

**Comment by upsuper** [comment]
It gives you all Matts who have any field contains "MacPherson"

**Comment by tofumatt** [comment]
Hmm, then I’d say it’s good :-)
- tofumatt

**Pull request merged**
