### PR TITLE
Check to confirm we have a valid ?mail= querystring parameter

### PR DESCRIPTION
**Pull request by rtucker-mozilla**
Per bug https://bugzilla.mozilla.org/show_bug.cgi?id=1214950

### CODE REVIEW

**Comment by tofumatt** [comment]
:cry: I don't have access to that bug, can you cc me on it so I can r?

**Comment by rtucker-mozilla** [comment]
I've added you as a cc

**Comment by tofumatt** [comment]
Cool, I simplified this a bit and merged it into master. I'll request a deploy of the new code in Bugzilla.

**Comment by rtucker-mozilla** [comment]
Awesome, thanks so much man. appreciate it!

**Comment by claudijd** [comment]
:+1:

**Pull request merged**
