### PR TITLE
Fix handling of search limits.

### PR DESCRIPTION
**Pull request by globau**
- handle limit checking and truncation directly instead for greater
  control
- generate "showing only the first N of Y results" html in the html
  output only

### CODE REVIEW

**Comment by floatingatoll** [comment]
Thank you for this!

**Comment by globau** [comment]
don't merge this yet - found some problems with this.

**Comment by globau** [comment]
sorted.

**Comment by globau** [comment]
r? @tofumatt 

this papers over some of the issues; i have another patch in the pipeline that shows "result limit reaches" warnings on all pages.

**Comment by tofumatt** [comment]
r+

**Pull request merged**
