### PR TITLE
Javascript rewrite.

### PR DESCRIPTION
**Pull request by globau**
After making a small change to the phonebook's javascript, knowledge of
it gnawed away at my psyche.  Always sitting in the back of my mind when
I looked up someone's phonebook entry was the complicated, obfuscated
tangle driving it.

Able to take it no more, here is the fruit of an otherwise idle weekend.

The primary goal of this change is to simplify the javascript, fixing
minor inconsistencies, with minimal php and template changes.  It aims
to have feature parity with the old code, however some parts operate
slightly differently where I felt appropriate.

### CODE REVIEW

**Comment by globau** [comment]
r? @tofumatt 

this is a large change.  i've tested it as much as i could, but it putting it through its paces locally or on stage is recommended.

**Comment by tofumatt** [comment]
Whoa, neato. I'll totally review this, but because of other commitments and our bad phonebook deploy system (and an unrelated and nice patch going out soon), I'll have to look in a few days. Sorry for the delays!

**Comment by floatingatoll** [comment]
I decided not to pull this into this week's deployment of Phonebook, as "significant rewrite" earns more testing than average. Will check in again in 1-4 weeks.

**Comment by floatingatoll** [comment]
Also - we're running production from mozilla-it/phonebook now, so that it's possible to do hotfixes and stuff without importing the entire mainline master branch from here. So y'all are welcome to merge to master any time without risk to production, so that the code deploys to phonebook-dev for live testing.

**Comment by globau** [comment]
hey @tofumatt ..  any chance of a review here? :)

**Comment by tofumatt** [comment]
Hey @globau,

I'd be game, but it's probably something I'll have to delay until maybe December if I'm honest. Since it's a short quarter with holidays and the all-hands–we're trying to get our AMO frontend goals all finished by December.

After that I'll have a look, but before then I just won't have time. Sorry 😢

**Comment by floatingatoll** [comment]
b05fee413316c80bd7678210738b78e44c7935a6 alters the ```no-results``` section to operate in a way that doesn't use inline-styles, which fixes a bug where there were two cats under strict CSP.

**Comment by floatingatoll** [comment]
616c92cb01d2375f03728cbde0b37f5fe2c1be9c alters the ```Clear``` button to work without inline styles.

**Comment by floatingatoll** [comment]
@globau I ported your rewrite forward the hard way (reapply all commits since on top of it, and then port it forward one commit at a time) to produce cb784d5fa716c01f4c669e9170455f738b38ab3d which applies cleanly to mozilla/master, and is live at phonebook-stage now. It has the two slight fixes above about CSP, and I believe I also cleaned out an XHTML trailing / that we added since then. Org tree search isn't searching the no-manager employees, working on that still.

**Comment by floatingatoll** [comment]
After testing, revised replacement commit d740bf9035cb99e8bc0ff2d1fea44e4542822692 (total rewrite, some merge errors resolved) and bonus XHR error display-handling commit adf5710f296a66196ded2dd6cf6c4aacf6d960ca.

**Comment by floatingatoll** [comment]
Ported forward again. I'm going to open a new PR and merge this.

0650fb2 Show an error when we don't complete the XHR. [#1301292]
b4b948c Javascript rewrite.

**Pull request closed without merging**
